###
GET http://localhost:5193/games

###
GET http://localhost:5193/games/3

###
POST http://localhost:5193/games
Content-Type: application/json

{
    "name": "Starfield",
    "genreId": 2,
    "price": 69.99,
    "releaseDate": "2023-09-06"
}

###
PUT http://localhost:5193/games/3
Content-Type: application/json

{
    "name": "Pure Farming",
    "genreId": 3,
    "price": 19.99,
    "releaseDate": "2020-09-07"
}

###
DELETE http://localhost:5193/games/2

###
GET http://localhost:5193/hello